[package]
name = "theme"
version = "0.1.0"
authors = ["Mike Kr√ºger <mkrueger@posteo.de>"]
edition = "2021"
publish = false

[dependencies]
iced.workspace = true
iced.default-features = true
iced_core.workspace = true
iced_core.features = ["serde"]
rfd.workspace = true
