[package]
name = "theme"
version = "0.1.0"
authors = ["Mike Kr√ºger <mkrueger@posteo.de>"]
edition = "2021"
publish = false

[dependencies]
icy_ui.workspace = true
icy_ui.default-features = true
icy_ui_core.workspace = true
icy_ui_core.features = ["serde"]
rfd.workspace = true
