[package]
name = "scrollable"
version = "0.1.0"
authors = ["Mike Kr√ºger <mkrueger@posteo.de>"]
edition = "2024"
publish = false

[dependencies]
icy_ui.workspace = true
icy_ui.features = ["debug", "canvas"]
