[package]
name = "accessibility"
version = "0.1.0"
authors = ["icy contributors"]
edition = "2024"
publish = false

[dependencies]
icy_ui.workspace = true
icy_ui.features = ["accessibility", "advanced"]
